name: ui_widgets
description: "A new Flutter project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  foundation:
    path: ../foundation
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  photo_view: ^0.15.0
  pinput: ^5.0.0
  syncfusion_flutter_core: ^28.1.33
  syncfusion_flutter_pdfviewer: ^28.1.33
  video_player: ^2.9.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
#  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: S