name: web_services
description: "A new Flutter project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  connectivity_plus: ^6.1.1
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  rxdart: ^0.28.0


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner:
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: S
