name: foundation
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  device_info_plus: ^10.1.0
  file_picker: 8.1.4
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_multi_formatter: ^2.13.0
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  package_info_plus: ^8.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
#  generate: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  assets:
    outputs:
      package_parameter_enabled: true # <- Add this line.

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter_intl:
  enabled: true
  class_name: S